import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Toaster } from "sonner";
import { ClientProviders } from "@/lib/ClientProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientProviders>
        <body className={inter.className} suppressHydrationWarning={true}>
          <Header />
          {children}
          <Footer />
          <Toaster position="top-right" />
        </body>
      </ClientProviders>
    </html>
  );
}
